CREATE DATABASE IF NOT EXISTS test;

CREATE  TABLE IF NOT EXISTS `students` (
  `id` BIGINT UNSIGNED AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `roll` INT NOT NULL UNIQUE,
  `maths` TINYINT UNSIGNED NOT NULL,
  `physics` TINYINT UNSIGNED NOT NULL,
  `chemistry` TINYINT UNSIGNED NOT NULL,
  `total` SMALLINT UNSIGNED NOT NULL,
  `percentage` DECIMAL(5,2) UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`));
